export const products = [
  {
    id: '1',
    name: 'Wireless Mouse',
    price: '$25',
    image: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRIjqMTCg7UjNi48kwEgCSxadlwJlok9pkJmA&s',
    details: 'A sleek wireless mouse with ergonomic design and long battery life, perfect for productivity and gaming.',
  },
  {
    id: '2',
    name: 'Mechanical Keyboard',
    price: '$85',
    image: 'https://media.istockphoto.com/id/1313504623/photo/rainbow-keyboard-gaming-keyboard-with-rgb-light-backlit-keyboard-in-a-dark-room-copy-space.jpg?s=612x612&w=0&k=20&c=97HFzOCdY6zRjMp-Hp9LzO6zYCRwH2_YflQsXP5gRV8=',
    details: 'Durable mechanical keyboard with customizable RGB backlighting and tactile key switches.',
  },
  {
    id: '3',
    name: 'HD Monitor',
    price: '$180',
    image: 'https://images.unsplash.com/photo-1593642532973-d31b6557fa68?auto=format&fit=crop&w=600&q=80',
    details: '24-inch Full HD monitor with vibrant colors, low blue light, and an adjustable stand.',
  },
  {
    id: '4',
    name: 'USB-C Hub',
    price: '$30',
    image: 'https://m.media-amazon.com/images/I/61QbS525pgL.jpg',
    details: 'Multi-port USB-C hub with HDMI, USB 3.0, SD card reader, and PD charging support.',
  },
  {
    id: '5',
    name: 'Gaming Headset',
    price: '$70',
    image: 'https://m.media-amazon.com/images/I/61LhfQRdEgL.jpg',
    details: 'Surround sound gaming headset with noise-canceling mic and comfortable ear cushions.',
  },
  {
    id: '6',
    name: 'Webcam Full HD',
    price: '$60',
    image: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRRuk9I16Yj7flmSb5mXkw3I4Ztfp1O3Yfalg&s',
    details: '1080p webcam with built-in microphone and wide-angle lens for clear video calls.',
  },
  {
    id: '7',
    name: 'Laptop Stand',
    price: '$35',
    image: 'https://symplify.in/cdn/shop/products/Wooden-Laptop-Stand-Opt3-3.jpg?v=1658253933',
    details: 'Aluminum adjustable laptop stand to improve posture and airflow.',
  },
  {
    id: '8',
    name: 'Portable SSD',
    price: '$120',
    image: 'https://cdn.thewirecutter.com/wp-content/media/2023/06/portableSSDs-2048px-4747-2x1-1.jpg?width=2048&quality=75&crop=2:1&auto=webp',
    details: '1TB portable SSD with fast data transfer and compact design for on-the-go storage.',
  },
  {
    id: '9',
    name: 'Bluetooth Speaker',
    price: '$55',
    image: 'https://m.media-amazon.com/images/I/71GNqOPWAuL._UF1000,1000_QL80_.jpg',
    details: 'Compact Bluetooth speaker with rich bass, waterproof build, and 12-hour battery life.',
  },
  {
    id: '10',
    name: 'Smartwatch',
    price: '$140',
    image: 'https://gourban.in/cdn/shop/files/Go.png?v=1705564072&width=2048',
    details: 'Feature-packed smartwatch with fitness tracking, heart rate monitor, and app notifications.',
  },
  {
    id: '11',
    name: 'Tablet Stand',
    price: '$25',
    image: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRncE2aCJux7w0nDWUCpoumacomsZ3_bu1JGw&s',
    details: 'Foldable stand for tablets and phones, perfect for video calls or reading.',
  },
  {
    id: '12',
    name: 'Ergonomic Chair',
    price: '$220',
    image: 'https://thesleepcompany.in/cdn/shop/files/1_3426fabe-ca94-4c07-8045-acdc75ae6ba4.webp?v=1750963026&width=860',
    details: 'Ergonomic office chair with lumbar support, mesh back, and adjustable height.',
  },
];
